# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: metrics.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'metrics.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rmetrics.proto\x12\x0blogpipeline\"\"\n\x0eMetricsRequest\x12\x10\n\x08\x65ndpoint\x18\x01 \x01(\t\"a\n\x0fMetricsResponse\x12\x10\n\x08\x65ndpoint\x18\x01 \x01(\t\x12\x15\n\rtotalRequests\x18\x02 \x01(\x05\x12\x12\n\nerrorCount\x18\x03 \x01(\x05\x12\x11\n\terrorRate\x18\x04 \x01(\x01\"\x1f\n\rAlertsRequest\x12\x0e\n\x06\x61\x63tive\x18\x01 \x01(\x08\"S\n\x05\x41lert\x12\x10\n\x08\x65ndpoint\x18\x01 \x01(\t\x12\x10\n\x08severity\x18\x02 \x01(\t\x12\x11\n\terrorRate\x18\x03 \x01(\x01\x12\x13\n\x0btriggeredAt\x18\x04 \x01(\t\"4\n\x0e\x41lertsResponse\x12\"\n\x06\x61lerts\x18\x01 \x03(\x0b\x32\x12.logpipeline.Alert\"+\n\x0bLogsRequest\x12\r\n\x05limit\x18\x01 \x01(\x05\x12\r\n\x05level\x18\x02 \x01(\t\"O\n\x08LogEntry\x12\x11\n\ttimestamp\x18\x01 \x01(\t\x12\r\n\x05level\x18\x02 \x01(\t\x12\x10\n\x08\x65ndpoint\x18\x03 \x01(\t\x12\x0f\n\x07message\x18\x04 \x01(\t\"3\n\x0cLogsResponse\x12#\n\x04logs\x18\x01 \x03(\x0b\x32\x15.logpipeline.LogEntry2\xe3\x01\n\x12LogPipelineService\x12G\n\nGetMetrics\x12\x1b.logpipeline.MetricsRequest\x1a\x1c.logpipeline.MetricsResponse\x12\x44\n\tGetAlerts\x12\x1a.logpipeline.AlertsRequest\x1a\x1b.logpipeline.AlertsResponse\x12>\n\x07GetLogs\x12\x18.logpipeline.LogsRequest\x1a\x19.logpipeline.LogsResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'metrics_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_METRICSREQUEST']._serialized_start=30
  _globals['_METRICSREQUEST']._serialized_end=64
  _globals['_METRICSRESPONSE']._serialized_start=66
  _globals['_METRICSRESPONSE']._serialized_end=163
  _globals['_ALERTSREQUEST']._serialized_start=165
  _globals['_ALERTSREQUEST']._serialized_end=196
  _globals['_ALERT']._serialized_start=198
  _globals['_ALERT']._serialized_end=281
  _globals['_ALERTSRESPONSE']._serialized_start=283
  _globals['_ALERTSRESPONSE']._serialized_end=335
  _globals['_LOGSREQUEST']._serialized_start=337
  _globals['_LOGSREQUEST']._serialized_end=380
  _globals['_LOGENTRY']._serialized_start=382
  _globals['_LOGENTRY']._serialized_end=461
  _globals['_LOGSRESPONSE']._serialized_start=463
  _globals['_LOGSRESPONSE']._serialized_end=514
  _globals['_LOGPIPELINESERVICE']._serialized_start=517
  _globals['_LOGPIPELINESERVICE']._serialized_end=744
# @@protoc_insertion_point(module_scope)
